server:
  port: 8989
  ssl:
    key-store-password: FZCBvGAJ73kHBgPL
    key-store-type: JKS
    key-store: classpath:0_www.softzeng.cn.jks
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://43.136.76.25:8014/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: JA%4MBTLAq^qs)@V?N4maHC,,Vf<yhKy
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 43.136.76.25
    port: 8013
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
oss:
  accessKey: hhWlyYcCQ2HPGxPDZHkzCl-M3p3SzDbnl0tl-nlp
  secretKey: iVP0h4D5ZVd8oi7uKtg9PVAS9hs3upug2io66eo-
  bucket: softzeng-blog